interfaceDjango/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls import re_path  # 写正则匹配
from web.views import Login
from web.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login),
    path('', include('web.urls')),
    path('', include('comments.urls')),

    # 记得在顶部引入 AllPostsRssFeed
    path('all/rss/', AllPostsRssFeed(), name='rss'),

    # 其它...
    path('search/', include('haystack.urls')),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    # path('', views.index, name='index'),
    # 设计文章详情页的 URL
    # path('posts/<int:pk>/', views.detail, name='detail'),
    # path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    # path('categories/<int:pk>/', views.category, name='category'),
    # path('tags/<int:pk>/', views.tag, name='tag'),

    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),

]

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
  <h3 class="widget-title">归档</h3>
  <ul>
    {% for date in date_list %}
      <li>
        <a href="{% url 'web:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
      </li>
    {% empty %}
      暂无归档！
    {% endfor %}
  </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
  <h3 class="widget-title">分类</h3>
  <ul>
    {% for category in category_list %}
      <li>
        <a href="{% url 'web:category' category.pk %}">
            {{ category.name }} <span class="post-count">({{ category.num_posts }})</span>
        </a>
      </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
  <h3 class="widget-title">最新文章</h3>
  <ul>
    {% for post in recent_post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% empty %}
      暂无文章！
    {% endfor %}
  </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{% url 'web:tag' tag.pk %}">
                    {{ tag.name }} <span class="post-count">({{ tag.num_posts }})</span>
                </a>
            </li>
        {% empty %}
            暂无标签！
        {% endfor %}
    </ul>
</div>